### ISSUE TITLE
Create a script to update plugins

### ISSUE THREAD

**Issue by nlMeminger** [jflory7/infrastructure#1]
create a script to update all the plugins using command line parameters

**Comment by jflory7** [comment]
Going to add some more info to the issue from some of the in-person discussion we had, so when we revisit this, we don't forget all of those things. 😃 

# Summary

We need a script to quickly and easily update plugins used on the servers.

# Analysis

There's a few things to consider for this one. The way the servers are currently set up is to use a single directory where all the plugins are stored. The script should probably use a local config file to use a variable for where the Spigot plugins are saved. This way, when the script is first used, you can set the location of the plugin directory before using it. And if it changes in the future, you won't have to manually edit the script.

Additionally, plugins come from all different places, and they also use different names than how they are saved in the server. It's important for the script to take two parameters, one for the "intended name" and one for the URL of where the plugin can be downloaded. The usage of this would be something like `wget -O $NAME $URL`, so then you could make sure the plugin is named as expected and you will pull the update from the right place.

We also discussed the idea of doing this in batches, so then you could pass multiple arguments and you could update several plugins in one go. I would call this an optional goal, though.

**Comment by jflory7** [comment]
Since I'm moving away from Minecraft server administration, I'm closing this as `wontfix`.
